blogg/urls.py
from django.urls import path
from . import views


app_name = 'blogg'

urlpatterns = [

    path('', views.all_bloggs, name = 'all_bloggs'),
    path('<int:blog_id>/', views.detail, name = 'detail'),

]

portfoliooo/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from myportfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blogg/', include('blogg.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogg/models.py
from django.db import models

# Create your models here.
class blog(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=250)
    date = models.DateTimeField()

    def __str__(self):
        return self.title

myportfolio/models.py
from django.db import models

# Create your models here.
class personalport(models.Model):
    title = models.CharField(max_length=120)
    description = models.CharField(max_length=250)
    picture = models.ImageField(upload_to='portfolioo/pictures/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blogg/views.py
from django.shortcuts import render, get_object_or_404
from .models import blog

# Create your views here.
def all_bloggs(request):
    blogs = blog.objects.order_by('-date')
    return render(request, 'blogg/all_bloggs.html',{'blogs':blogs})

def detail(request, blog_id):
    blogg = get_object_or_404(blog, pk=blog_id)
    return render(request, 'blogg/detail.html',{'blogg':blogg})

myportfolio/views.py
from django.shortcuts import render
from .models import personalport
# Create your views here.
def home(request):
    projects = personalport.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blogg/templates/blogg/all_bloggs.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-centre mb-5">dharam has Written {{blogs.count}} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs    %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">


    <a href="{% url 'blogg:detail' blog.id %}">
        <h2>{{  blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{  blog.date}}</h5>
    <h4>{{  blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>

    {% endfor %}
{%  endblock  %}

blogg/templates/blogg/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

    <h1 class="text-center mt-5" id="blogdetailtitle">{{ blogg.title }}</h1>


    <h5 class="text-center text-muted mb-5">{{  blogg.date  }}</h5>


    <h4>{{ blogg.description|safe}}</h4>

{%  endblock  %}

myportfolio/templates/portfolio/base.html
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">

  <title>Dharamraj Jadeja</title>
</head>
<body>
<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/Logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Dharam's Logo">
        <span>Dharamraj Jadeja</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/dharamresume.pdf' %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/dharam-raj-sinh-jadeja-7111b9193/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/endercoder23" target="_blank">Github</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.instagram.com/dharamrajjadeja23/" target="_blank">Instagram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/dharamrajsingh.jadeja" target="_blank">Facebook</a>
          </li>

          <li>
            <a role="button" href="{% url 'blogg:all_bloggs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">

{%  block content  %}{%  endblock  %}
<meta charset="UTF-8">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </div>
</body>
</html>

myportfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/dharam.jpg' %}" class="img-fluid">
  </div>
</div>
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Dharam's portfolio</h1>
  </div>
</div>




<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.picture.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.picture.url }}" class="img-fluid mb-2">
    {% endif %}
      <h3>{{ project.title }}</h3>

    <p>{{ project.description }}</p>

  </div>

    {% endfor %}
</div>
{% endblock %}